### PR TITLE
#Ng-445: [BUG] When opening some projects, the Project Info page opens in the middle, and you need to scroll up to see all the information

### LINKED ISSUE #445: [BUG] When opening some projects, the Project Info page opens in the middle, and you need to scroll up to see all the information.
**Steps to Reproduce:**

1. Open app: https://indigo-eln-dev.test.lifescience.opensource.epam.com/ and login (e.g. as [alice@eln.com](mailto:alice@eln.com)) 
2. Open some project. e.g "New project N33"
3. Observe the action

**Actual result:** 
When opening some projects, the Project Info page opens in the middle, and you need to scroll up to see all the information.
https://github.com/user-attachments/assets/11c2654d-e804-4990-9669-dffa557720c0

_Note! This doesn't happen for all projects, but the scrollbar is present on all pages._

Image

**Expected result:** 
When all information is displayed without the need to scroll, the appearance of a scrollbar becomes redundant.

### PR DESCRIPTION
**Pull request by GIGAKLIBADZE**
This bug: https://github.com/orgs/epam/projects/41/views/1?filterQuery=giga&pane=issue&itemId=145739318&issue=epam%7CIndigo-ELN-v.-2.0%7C445 is fixed by removing the vertical scrollbar at all when that is no need to scroll down, it properly responses to the QA report.

When there is necessary t boe a scrollbar then it appears and appears  at the top.

### CODE REVIEW

File: indigo-frontend/src/core/components/layout/master.component.ts [hunk 1]
```diff
@@ -53,6 +56,11 @@ export class MasterComponent implements OnInit, OnDestroy {
     this.userService.user$.pipe(takeUntil(this.destroy$)).subscribe((user) => {
       this.userName = `${user.displayName}`;
     });
+
+    (this.router.events as Observable<NavigationEnd>).pipe(filter((e) => e instanceof NavigationEnd))
```
Comment (aamialkovich) [inline indigo-frontend/src/core/components/layout/master.component.ts]: shouldn't we make unsubscription here?

Comment (GIGAKLIBADZE) [reply indigo-frontend/src/core/components/layout/master.component.ts]: Fixed.

**Review by aamialkovich — APPROVED** [review]
